export const FETCH_FOOD_LIST = 'FETCH_FOOD_LIST';
export const FETCH_FOOD_LIST_KO= 'FETCH_FOOD_LIST_KO';
export const FETCH_FOOD_LIST_OK = 'FETCH_FOOD_LIST_OK';

export const FETCH_FOOD_INFO = 'FETCH_FOOD_INFO';
export const FETCH_FOOD_INFO_OK= 'FETCH_FOOD_INFO_OK';
export const FETCH_FOOD_INFO_KO = 'FETCH_FOOD_INFO_KO';

export const UPDATE_FOOD_NUTRIENTS = 'UPDATE_FOOD_NUTRIENTS';
export const UPDATE_FOOD_NUTRIENTS_OK = 'UPDATE_FOOD_NUTRIENTS_OK';
export const UPDATE_FOOD_NUTRIENTS_KO = 'UPDATE_FOOD_NUTRIENTS_KO';

export const DELETE_DIET = 'DELETE_DIET';
export const DELETE_DIET_OK = 'DELETE_DIET_OK';

export const RESET_ERRORS = 'RESET_ERRORS';
export const ADD_FOOD_DIET = 'ADD_FOOD_DIET';
export const SAVE_FOOD = 'SAVE_FOOD';
export const CREATE_DIET = 'CREATE_DIET';
export const UPDATE_FOOD_QUANTITY = 'UPDATE_FOOD_QUANTITY';
export const DELETE_FOOD = 'DELETE_FOOD';
export const RESET_FOOD_LIST = 'RESET_FOOD_LIST';
